### ISSUE TITLE
Specific version status isn't checked

### ISSUE THREAD

**Issue by lizzard** [lmandel/ReleaseHealth#3]
For the blocking bugs at https://lmandel.github.io/ReleaseHealth/?channel=aurora, I should be seeing this bug right now: https://bugzilla.mozilla.org/show_bug.cgi?id=1242641 But it isn't listed. I suspect that might be because you're checking the overall status of the bug rather than status-firefox46.

**Comment by lizzard** [comment]
Hmm no, in https://github.com/lmandel/ReleaseHealth/blob/master/js/releasehealth.js you are checking status-firefox{RELEASE} but checking to see if it's set to ---    Probably that should be affected or ---. or anything that isn't fixed, verified, or disabled.

**Comment by lmandel** [comment]
Good catch. In fact https://bugzilla.mozilla.org/show_bug.cgi?id=1247741 should be on the list as well. The problem is that the query is checking for resolved state of the bug and should be checking the state of the status flag.
